### ISSUE TITLE
Inject dependency on a Typer function

### ISSUE THREAD

**Issue by davidbrochart** [pyapp-kit/in-n-out#58]
* in-n-out version: 0.1.6
* Python version: 3.11
* Operating System: Ubuntu 22.04

### Description

The following code:
```py
import in_n_out as ino
import typer

class Thing:
    pass

@ino.inject
def main(name: str, thing: Thing):
    print(f"Hello {name}")

if __name__ == "__main__":
    typer.run(main)
```
Fails with `RuntimeError: Type not yet supported: <class '__main__.Thing'>`, probably because Typer also inspects the `main` function signature, which doesn't play well with in-n-out.
There is a workaround:
```py
def main(name: str):
    @ino.inject
    def inner(thing: Thing):
        print(f"Hello {name}")
    inner()
```
But curious to know if you can think of a better solution?

**Comment by tlambert03** [comment]
yeah, I don't think this one is going to be possible, but i think it's more of a typer limitation than in-n-out, and I don't think there's anything (safe) we could do to help it along.

if I'm not mistaken, typer just doesn't support custom types?  https://github.com/tiangolo/typer/issues/77
so, as you no doubt found, removing in-n-out altogether from the example still gives the `Type not yet supported error` when typer encounters `thing: Thing` in the signature. 

The very best we could do (and I don't like it) is to patch the `__signature__` attribute of an in-n-out injected function to essentially *remove* injected types from the signature, so that typer simply doesn't see them when it inspects signatures here: https://github.com/tiangolo/typer/blob/50caff27573e0d1381701d24122ca9fed20d6343/typer/main.py#L548

... the problem with that is
1. it's a lie: the parameters *are* still in the signature, and in-n-out _does_ allow you to pass them to the function if you wish to override injection when calling the function.
2. we actually don't know _which_ parameters will be injected (at injection time).  we only know it at call time (since providers can be registered at any point, even after decorating a function with `ino.inject`).  So, even if we wanted to remove something, we wouldn't know it was `thing` that needed to be removed.

Since typer is it's own dependency injection system, this one is probably going to be tough to pull off.  but perhaps if https://github.com/tiangolo/typer/issues/77 is addressed, we could extend support for it
